dist: trusty
sudo: required
language: node_js
node_js:
- '4'
- '6'
- '8'
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
script:
- npm test -- --coverage
after_script:
- if [[ "$TRAVIS_PULL_REQUEST" == "false" && `node --version` == *v8* ]]; then ./cc-test-reporter
  after-build --exit-code $TRAVIS_TEST_RESULT; fi
env:
  global:
    secure: Uidl2ix7gMcbTAgUzL7HG8hayWaehllo1sMDA/T8u/sU7IMw0JRNj7voOSWJ/WxTPIQofEeNdCHWsJxg/j8B4LnCcZHpr64gclMyReqLirpIHQSApusApwYINt+9sLyJMcm/xjdjZlZdXGf2c/jmFe8u80i1vznnbO09A0VdUqVS99I+x/0untA7UNtes4O+4yNTU6fh9aPndv+hGni37nujnub/Wegb2oRXLj2osU5D2mDmUcYTEarZWioixJ2eIB7gDD0AYujHyg9OwncJ10EVn/krFV4tfmw0A7xQpbX+NHwyGUc59b90oPtccTawViViPpu8IHTSsYXViVtw7yd8ydDi67MPSCUp35jY6XzLdI52MgYOeqkz9TEAF1dcOkcVqxuLt0JI49YWa93Wdd4fWJQy3EZvSkMsppXYDUuRFMl1LjwT5AYrjpNuGWnKDodVSfJS3pilSOwvpk18yUJPyKNsGZ63c+PsYwqnpnyWjuoH3mkBYvp0zOWxtiWLUf1Ijty3tue5cS+9StO3fpvARm6FAgrqSZFJm2QWskC/Onjx9oNq6IL9nzBKunMK8ZFbmiVo4NdeulY8ve2++DOZ0Cv/CnSdhzFpuwQVFgawJsrZW/sLFs5pqu+bBV+nWN9BurlmZ6cVRXbh6MZoV5NucCQINj2aDJFiIilESLM=
